### ISSUE TITLE
running HClient

### ISSUE THREAD

**Issue by glennpierce** [skyfoundry/haystack-java#4]
How can I actually run HClient from a linux console.

after running ./gradlew build successfully 

I then try to call

`java -jar build/libs/haystack-java-3.0.5.jar org.projecthaystack.client.HClient http://127.0.0.1:4337 user pencel`

but I just get

`no main manifest attribute, in build/libs/haystack-java-3.0.5.jar`

I am new to gradle and its been many years since I touched Java. Trying to test against my server implementation.

Thanks

**Comment by mgiannini** [comment]
Use the `-cp` option instead of `-jar`

`java -cp build\libs\haystack-java-3.0.5.jar org.projecthaystack.client.HClient`
