### ISSUE TITLE
HDateTimeRangeTest fails if HDate.today() != today in New York

### ISSUE THREAD

**Issue by jlittlenz** [skyfoundry/haystack-java#5]
```
> Task :test FAILED

Gradle suite > Gradle test > org.projecthaystack.HDateTimeRangeTest > testRange
Gradle suite > Gradle test > org.projecthaystack.HDateTimeRangeTest > testRange
FAILED
    java.lang.AssertionError at HDateTimeRangeTest.java:38
```
The test uses the "New York" time zone.  Here being 17-19 hours ahead of New York , HDate.today() is usually the day after today in New York.  Changing the time zone string to the local one lets the test pass.

**Comment by mgiannini** [comment]
Hi @jlittlenz - commit e5618feed6cd7d53711fa1926308dbca254a17ac closes issue #5
