### ISSUE TITLE
Time Units Missing

### ISSUE THREAD

**Issue by jhughesbiot** [skyfoundry/haystack-java#7]
Would it be possible to get the full list of time units defined into HNum when calculating duration?  You can see from the image below that only a subset of them are defined in the millis function but there are more defined by haystack.  At the very least, day should be implemented to keep in line with SkySpark's implementation of Duration which essentially does the same thing as this function but includes day as a valid unit.

![image](https://user-images.githubusercontent.com/50999916/111210056-02917400-858a-11eb-88fa-64d78d09be2d.png)

**Comment by mgiannini** [comment]
@jhughesbiot commit 977612b fixes issue #7
