### ISSUE TITLE
Question - HClient thread safety

### ISSUE THREAD

**Issue by a-hansen** [skyfoundry/haystack-java#9]
Can a single instance of HClient support parallel requests?

**Comment by briansfrank** [comment]
Hey Aaron,

The watches stuff doesn't look synchronized, so that might not be thread safe.

But just quickly looking thru it everything routes down to postString which seems to be thread safe since each caller creates fresh instance of HttpURLConnection

**Comment by a-hansen** [comment]
Awesome and thanks.  Hope all is well.
